The goal of this competition is to predict which product, if any, a customer will purchase in the following month

In [1]:
import pandas as pd
import numpy as np

import gc; gc.enable()

In [ ]:
# Counting the number of rows in the file without importing the file

# with open('train_ver2.csv') as f:
#     print(sum(1 for row in f))

In [2]:
df = pd.read_csv('train_ver2.csv', nrows=10)

In [3]:
# Unit 8 has a capacity to store values from 0 to 255. I am going to use this instead of int64 that has a capacity-9,223,372,036,854,775,808 to +9,223,372,036,854,775,807
# changing the dates to datetype
# changing floats to float32
# The rest of the objects I am going to make  into float32

In [4]:
# creaing a dictionary of with the features and their datatypes
types = {}
for c in df.columns.tolist():
     types[c] = df[c].dtype

In [5]:
# age, indrel_1mes, antiguedad, conyuemp
newtype = {'fecha_dato': 'str',
 'ncodpers': 'int32',
 'ind_empleado': 'str',
 'pais_residencia': 'str',
 'sexo': 'str',
 'age': 'str',
 'fecha_alta': 'str',
 'ind_nuevo': 'float32',
 'antiguedad': 'str',
 'indrel': 'float32',
 'ult_fec_cli_1t': 'str',
 'indrel_1mes': 'str',
 'tiprel_1mes': 'str',
 'indresi': 'str',
 'indext': 'str',
 'conyuemp': 'str',
 'canal_entrada': 'str',
 'indfall': 'str',
 'tipodom': 'float32',
 'cod_prov': 'float32',
 'nomprov': 'str',
 'ind_actividad_cliente': 'float32',
 'renta': 'float32',
 'segmento': 'str',
 'ind_ahor_fin_ult1': 'uint8',
 'ind_aval_fin_ult1': 'uint8',
 'ind_cco_fin_ult1': 'uint8',
 'ind_cder_fin_ult1': 'uint8',
 'ind_cno_fin_ult1': 'uint8',
 'ind_ctju_fin_ult1': 'uint8',
 'ind_ctma_fin_ult1': 'uint8',
 'ind_ctop_fin_ult1': 'uint8',
 'ind_ctpp_fin_ult1': 'uint8',
 'ind_deco_fin_ult1': 'uint8',
 'ind_deme_fin_ult1': 'uint8',
 'ind_dela_fin_ult1': 'uint8',
 'ind_ecue_fin_ult1': 'uint8',
 'ind_fond_fin_ult1': 'uint8',
 'ind_hip_fin_ult1': 'uint8',
 'ind_plan_fin_ult1': 'uint8',
 'ind_pres_fin_ult1': 'uint8',
 'ind_reca_fin_ult1': 'uint8',
 'ind_tjcr_fin_ult1': 'uint8',
 'ind_valo_fin_ult1': 'uint8',
 'ind_viv_fin_ult1': 'uint8',
 'ind_nomina_ult1': 'float32',
 'ind_nom_pens_ult1': 'float32',
 'ind_recibo_ult1': 'uint8'}

In [6]:
cols = list(newtype.keys())

In [7]:
df= pd.read_csv('train_ver2.csv', usecols=cols, dtype = newtype)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13647309 entries, 0 to 13647308
Data columns (total 48 columns):
fecha_dato               object
ncodpers                 int32
ind_empleado             object
pais_residencia          object
sexo                     object
age                      object
fecha_alta               object
ind_nuevo                float32
antiguedad               object
indrel                   float32
ult_fec_cli_1t           object
indrel_1mes              object
tiprel_1mes              object
indresi                  object
indext                   object
conyuemp                 object
canal_entrada            object
indfall                  object
tipodom                  float32
cod_prov                 float32
nomprov                  object
ind_actividad_cliente    float32
renta                    float32
segmento                 object
ind_ahor_fin_ult1        uint8
ind_aval_fin_ult1        uint8
ind_cco_fin_ult1         uint8
ind_cder_fin_ult1        uint8
ind_cno_fin_ult1         uint8
ind_ctju_fin_ult1        uint8
ind_ctma_fin_ult1        uint8
ind_ctop_fin_ult1        uint8
ind_ctpp_fin_ult1        uint8
ind_deco_fin_ult1        uint8
ind_deme_fin_ult1        uint8
ind_dela_fin_ult1        uint8
ind_ecue_fin_ult1        uint8
ind_fond_fin_ult1        uint8
ind_hip_fin_ult1         uint8
ind_plan_fin_ult1        uint8
ind_pres_fin_ult1        uint8
ind_reca_fin_ult1        uint8
ind_tjcr_fin_ult1        uint8
ind_valo_fin_ult1        uint8
ind_viv_fin_ult1         uint8
ind_nomina_ult1          float32
ind_nom_pens_ult1        float32
ind_recibo_ult1          uint8
dtypes: float32(8), int32(1), object(17), uint8(22)
memory usage: 2.5+ GB

In [9]:
frames = []
for dato in df['fecha_dato'].unique().tolist():
    df_dato = df.loc[df['fecha_dato'] == dato].copy().sample(frac=0.10)
    frames.append(df_dato)
    gc.collect()

In [ ]:
len(frames)

In [10]:
trial = pd.concat(frames)

In [ ]:
trial.to_csv('df_sample.csv')

## EDA

In [ ]:
# column fecha dato shows the day in which the transaction happened

In [11]:
used_cols = ['ind_ahor_fin_ult1', 'ind_aval_fin_ult1', 'ind_cco_fin_ult1', 'ind_cder_fin_ult1', 'ind_cno_fin_ult1', 'ind_ctju_fin_ult1', 'ind_ctma_fin_ult1',
 'ind_ctop_fin_ult1', 'ind_ctpp_fin_ult1', 'ind_deco_fin_ult1', 'ind_deme_fin_ult1', 'ind_dela_fin_ult1', 'ind_ecue_fin_ult1', 'ind_fond_fin_ult1',
 'ind_hip_fin_ult1', 'ind_plan_fin_ult1', 'ind_pres_fin_ult1', 'ind_reca_fin_ult1', 'ind_tjcr_fin_ult1', 'ind_valo_fin_ult1', 'ind_viv_fin_ult1',
 'ind_nomina_ult1', 'ind_nom_pens_ult1', 'ind_recibo_ult1']

col_name = ['Saving Acount', 'Guarantees', 'Current Accounts', 'Derivada Accounts', 'Payroll Account', 'Junior Account', 'Mas particular Account',
           'particular Account', 'particular Plus Account', 'Short_term Deposits', 'Medium-term Deposits', 'Long-term Deposits', 'e-account', 'Funds',
           'Mortgage', 'Pensions', 'Pensions', 'Loans', 'Taxes', 'Credit Card', 'Securities', 'Home Account', 'Payroll', 'Pensions', 'Direct Debit']

In [ ]:
i = 0
for c in filtered_df[used_cols]:
    values = filtered_df[c].value_counts()
    print(col_name[i])
    i += 1
    print(values)
    print('\n')

In [12]:
for c in df.columns.tolist():
    df[c].fillna(df[c].mode()[0], inplace=True)

In [ ]:
df.isnull().sum()

In [ ]:
#df = df[df['ind_empleado'] != 'S']

In [ ]:
# filtering to see clients that have pais_residencia missing. It shows that there isnt much information about these clients
#filtered_df = df[df['pais_residencia'].isnull()]

In [ ]:
#len(filtered_df['ncodpers'].unique())

In [ ]:
#df['pais_residencia'].fillna(df['pais_residencia'].mode()[0], inplace=True)

In [ ]:
#df['sexo'].fillna(df['sexo'].mode()[0], inplace=True)

In [ ]:
# transforming fecha_dato and fecha_alta into dates
df['fecha_dato'] = pd.to_datetime(df['fecha_dato'], format="%Y-%m-%d")
df['fecha_alta'] = pd.to_datetime(df['fecha_alta'], format="%Y-%m-%d")

In [ ]:
# Assuming that some customers may want to buy more depending on the time of the year, I am going to add another column
df['month'] = pd.DatetimeIndex(df['fecha_dato']).month

In [16]:
df[df['ind_plan_fin_ult1'] == df['ind_nom_pens_ult1']]

,fecha_dato,ncodpers,ind_empleado,pais_residencia,sexo,age,fecha_alta,ind_nuevo,antiguedad,indrel,...,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
0,2015-01-28,1375586,N,ES,H,35,2015-01-12,0.0,6,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
1,2015-01-28,1050611,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
2,2015-01-28,1050612,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
3,2015-01-28,1050613,N,ES,H,22,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
4,2015-01-28,1050614,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
5,2015-01-28,1050615,N,ES,H,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
6,2015-01-28,1050616,N,ES,H,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
7,2015-01-28,1050617,N,ES,H,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
8,2015-01-28,1050619,N,ES,H,24,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
9,2015-01-28,1050620,N,ES,H,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
10,2015-01-28,1050621,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
11,2015-01-28,1050622,N,ES,H,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
12,2015-01-28,1050623,N,ES,H,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13,2015-01-28,1050624,N,ES,H,65,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
14,2015-01-28,1050625,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
15,2015-01-28,1050626,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
16,2015-01-28,1050610,N,ES,V,24,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
17,2015-01-28,1050627,N,ES,H,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
18,2015-01-28,1050609,N,ES,H,22,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
19,2015-01-28,1050605,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
20,2015-01-28,1050582,N,ES,V,28,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
21,2015-01-28,1050586,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,1
22,2015-01-28,1050588,N,ES,H,22,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
23,2015-01-28,1050589,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
24,2015-01-28,1050591,N,ES,H,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
25,2015-01-28,1050592,N,ES,H,22,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
26,2015-01-28,1050595,N,ES,V,25,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
27,2015-01-28,1050596,N,ES,H,25,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
28,2015-01-28,1050597,N,ES,H,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
29,2015-01-28,1050598,N,ES,H,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13647279,2016-05-28,1166759,N,ES,H,22,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647280,2016-05-28,1166761,N,ES,H,23,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647281,2016-05-28,1166762,N,ES,V,22,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647282,2016-05-28,1166787,N,ES,H,23,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647283,2016-05-28,1166786,N,ES,H,23,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647284,2016-05-28,1166785,N,ES,V,23,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647285,2016-05-28,1166784,N,ES,H,23,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647286,2016-05-28,1166783,N,ES,H,25,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647287,2016-05-28,1166782,N,ES,V,23,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647288,2016-05-28,1166781,N,ES,H,24,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647289,2016-05-28,1166780,N,ES,H,28,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647290,2016-05-28,1166779,N,ES,V,23,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647291,2016-05-28,1166778,N,ES,V,23,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647292,2016-05-28,1166777,N,ES,V,23,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647293,2016-05-28,1166776,N,ES,H,23,2013-08-16,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647294,2016-05-28,1166775,N,ES,V,23,2013-08-16,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647295,2016-05-28,1166774,N,ES,H,22,2013-08-16,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647296,2016-05-28,1166773,N,ES,H,23,2013-08-16,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647297,2016-05-28,1166772,N,ES,V,23,2013-08-16,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647298,2016-05-28,1166771,N,ES,H,23,2013-08-16,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647299,2016-05-28,1166770,N,ES,H,23,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647300,2016-05-28,1166769,N,ES,H,26,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647301,2016-05-28,1166768,N,ES,V,23,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647302,2016-05-28,1166767,N,ES,V,25,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647303,2016-05-28,1166766,N,ES,V,25,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647304,2016-05-28,1166765,N,ES,V,22,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647305,2016-05-28,1166764,N,ES,V,23,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647306,2016-05-28,1166763,N,ES,H,47,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647307,2016-05-28,1166789,N,ES,H,22,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647308,2016-05-28,1550586,N,ES,H,37,2016-05-13,1.0,0,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0

# Missing values and action plan

ind_empleado - 27734. Employee index: A active, B ex employed, F filial, N not employee, P pasive. I am noticing that there is a value that is not in the description so I believe it is a typo. I tried looking more into the data but in the end I decided to drop since it is just one person. The nan values I am replacing with the mode which in this case it is that the person is not an employee.

df = df[df['ind_empleado'] != 'S']

-------------------------------------------------------
pais_residencia - 27734. One aspect that I found interesting is that clients with pais_residencia missing had all other features missing. I considered dropping them, but then decided not to because they are still potential clients in which we could recommend some products. For now I am going to replace the missing values with the mode. I considered dropping the missing values but these are 7000 customers with 27000 product purchase so they are potential targets

filtered_df = df[df['pais_residencia'].isnull()]
len(filtered_df['ncodpers'].unique())
This shows that there are 7340 without much information about them

-------------------------------------------------------
sexo - 27804. Most of the clients that have this information missing dont have much information on them overall. If we were to drop the ones that have most information missing, sexo would have about 70 values missing. For now I am going to change these with the mode.

-------------------------------------------------------
I need to turn fecha_dato and fecha_alta into dates

fecha_alta - 27734. This is the date that the customer joined the bank.
Added another column called month. May be useful in the case that some customers buy more depending on the time of the year.

-------------------------------------------------------
ind_nuevo                   27734
indrel                      27734
ult_fec_cli_1t           13622516
indrel_1mes                149781
tiprel_1mes                149781
indresi                     27734
indext                      27734
conyuemp                 13645501
canal_entrada              186126
indfall                     27734
tipodom                     27735
cod_prov                    93591
nomprov                     93591
ind_actividad_cliente       27734
renta                     2794375
segmento                   189368
ind_nomina_ult1             16063
ind_nom_pens_ult1           16063


-------------------------------------------------------
A bank guarantee is a lending institution's promise to cover a loss if a borrower (their customer) defaults on a debt to a third party. 

A payroll account is a separate bank account for your business that is strictly used for payroll. Instead of lumping all your business expenses into one account, you will pay employee wages with your payroll bank account. The money going into the payroll account will only be used for payroll.

Bank policy requires that account owners be the legal age of 18 in order to open an account online. If you are not 18 years old, you may open an account for minors with your parent or legal guardian as the joint account holder.

A pension plan is a type of retirement plan where an employee adds money into a fund that includes contributions by the employer.

A securities account sometimes known as a brokerage account is an account that holds financial assets such as securities on behalf of an investor with a bank, broker or custodian.

# Data Visualizations